### ISSUE TITLE
Fuzzing

### ISSUE THREAD

**Issue by lwwmanning** [spiraldb/vortex#129]
Once the codebase stabilizes more, a couple useful variants of fuzzing:

- rust-fuzz -- good for ensuring that we return Errors instead of panicking (panics should be for programmer error only)
- hypothesis (python) -- great for testing round-tripping of inputs & outputs at the user-facing API

Good example of rust-fuzz usage in croaring-rs: https://github.com/RoaringBitmap/croaring-rs/blob/master/fuzz/Cargo.toml 

We can get https://github.com/google/oss-fuzz to continuously run our fuzzing as well.

**Comment by robert3005** [comment]
Done partially in #600 #639 needs more functionality and integration into oss-fuzz
