### ISSUE TITLE
new / try_new / new_unchecked

### ISSUE THREAD

**Issue by gatesn** [spiraldb/vortex#42]
It's misleading to have `new()` call `try_new().unwrap()` since it obscures the lack of safety.

I'd propose we have a `new_unchecked` and `new() Result<...>` where unchecked can be used as an optimisation, otherwise the caller can explicitly call `new().unwrap()` and therefore it's obvious that it can panic.

**Comment by robert3005** [comment]
We have mostly got rid of try_new.unwrap. I think we should enforce no random unwraps
