### ISSUE TITLE
Look into Vortex date & time

### ISSUE THREAD

**Issue by gatesn** [spiraldb/vortex#92]
We should have:
• LocalTime ([time unit] after midnight) - Arrow time32 or time64
• LocalDate (julian day) - Arrow date32
• LocalDateTime (julian day and [time unit] after midnight) - Not supported by Arrow
• Instant ([time unit] since EPOCH) - Arrow date64, date32, or timestamp with absent tz.
• ZonedDateTime (struct{Instance, TZ}) - Arrow timestamp with present tz.

Should each of these arrays be their own encoding? They could just be implemented using "TypedArray".

**Comment by robert3005** [comment]
fixed in #480. We have arrow compatbility. We should add ZonedDateTime and LocalDateTime in the future
